import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Silk Hijabs',
    slug: 'silk-hijabs',
    description: 'Luxurious silk hijabs for special occasions',
  },
  {
    id: '2',
    name: 'Cotton Hijabs',
    slug: 'cotton-hijabs',
    description: 'Comfortable cotton hijabs for everyday wear',
  },
  {
    id: '3',
    name: 'Chiffon Hijabs',
    slug: 'chiffon-hijabs',
    description: 'Lightweight chiffon hijabs with elegant drape',
  },
  {
    id: '4',
    name: 'Jersey Hijabs',
    slug: 'jersey-hijabs',
    description: 'Stretchy jersey hijabs for active lifestyle',
  },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Silk Scarf',
    description: 'Premium silk hijab with beautiful patterns and luxurious feel. Perfect for special occasions and formal events.',
    price: 89.99,
    originalPrice: 120.00,
    images: [
      '/images/hijab-1-1.jpg',
      '/images/hijab-1-2.jpg',
      '/images/hijab-1-3.jpg',
    ],
    category: 'silk-hijabs',
    colors: ['Navy Blue', 'Burgundy', 'Forest Green', 'Charcoal'],
    sizes: ['One Size'],
    inStock: true,
    featured: true,
    tags: ['silk', 'luxury', 'formal', 'elegant'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Comfort Cotton Wrap',
    description: 'Soft and breathable cotton hijab perfect for daily wear. Easy to style and comfortable all day long.',
    price: 24.99,
    images: [
      '/images/hijab-2-1.jpg',
      '/images/hijab-2-2.jpg',
      '/images/hijab-2-3.jpg',
    ],
    category: 'cotton-hijabs',
    colors: ['White', 'Black', 'Beige', 'Light Blue'],
    sizes: ['One Size'],
    inStock: true,
    featured: true,
    tags: ['cotton', 'comfortable', 'daily', 'breathable'],
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    name: 'Flowing Chiffon Shawl',
    description: 'Lightweight chiffon hijab with elegant drape and beautiful flow. Perfect for summer and special occasions.',
    price: 34.99,
    originalPrice: 45.00,
    images: [
      '/images/hijab-3-1.jpg',
      '/images/hijab-3-2.jpg',
      '/images/hijab-3-3.jpg',
    ],
    category: 'chiffon-hijabs',
    colors: ['Rose Gold', 'Silver', 'Pearl White', 'Dusty Pink'],
    sizes: ['One Size'],
    inStock: true,
    featured: true,
    tags: ['chiffon', 'lightweight', 'elegant', 'summer'],
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '4',
    name: 'Active Jersey Hijab',
    description: 'Stretchy jersey hijab designed for active lifestyle. Stays in place during movement and activities.',
    price: 19.99,
    images: [
      '/images/hijab-4-1.jpg',
      '/images/hijab-4-2.jpg',
      '/images/hijab-4-3.jpg',
    ],
    category: 'jersey-hijabs',
    colors: ['Black', 'Navy', 'Gray', 'White'],
    sizes: ['One Size'],
    inStock: true,
    featured: false,
    tags: ['jersey', 'active', 'sporty', 'stretchy'],
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '5',
    name: 'Premium Silk Collection',
    description: 'Exclusive silk hijab with intricate patterns and premium quality. A statement piece for any wardrobe.',
    price: 129.99,
    originalPrice: 160.00,
    images: [
      '/images/hijab-5-1.jpg',
      '/images/hijab-5-2.jpg',
      '/images/hijab-5-3.jpg',
    ],
    category: 'silk-hijabs',
    colors: ['Royal Blue', 'Deep Purple', 'Emerald Green', 'Crimson'],
    sizes: ['One Size'],
    inStock: true,
    featured: true,
    tags: ['silk', 'premium', 'exclusive', 'statement'],
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '6',
    name: 'Classic Cotton Blend',
    description: 'Versatile cotton blend hijab that combines comfort with style. Perfect for both casual and semi-formal occasions.',
    price: 29.99,
    images: [
      '/images/hijab-6-1.jpg',
      '/images/hijab-6-2.jpg',
      '/images/hijab-6-3.jpg',
    ],
    category: 'cotton-hijabs',
    colors: ['Cream', 'Light Gray', 'Powder Blue', 'Soft Pink'],
    sizes: ['One Size'],
    inStock: true,
    featured: false,
    tags: ['cotton', 'versatile', 'classic', 'comfortable'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '7',
    name: 'Delicate Chiffon Wrap',
    description: 'Fine chiffon hijab with subtle patterns and beautiful transparency. Ideal for layering and elegant styling.',
    price: 39.99,
    originalPrice: 50.00,
    images: [
      '/images/hijab-7-1.jpg',
      '/images/hijab-7-2.jpg',
      '/images/hijab-7-3.jpg',
    ],
    category: 'chiffon-hijabs',
    colors: ['Ivory', 'Lavender', 'Mint Green', 'Blush'],
    sizes: ['One Size'],
    inStock: true,
    featured: false,
    tags: ['chiffon', 'delicate', 'layering', 'elegant'],
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '8',
    name: 'Sport Jersey Hijab',
    description: 'High-performance jersey hijab designed for sports and fitness activities. Moisture-wicking and breathable.',
    price: 22.99,
    images: [
      '/images/hijab-8-1.jpg',
      '/images/hijab-8-2.jpg',
      '/images/hijab-8-3.jpg',
    ],
    category: 'jersey-hijabs',
    colors: ['Black', 'White', 'Navy', 'Red'],
    sizes: ['One Size'],
    inStock: true,
    featured: false,
    tags: ['jersey', 'sport', 'fitness', 'moisture-wicking'],
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '9',
    name: 'Luxury Silk Embroidered',
    description: 'Hand-embroidered silk hijab with intricate details and premium craftsmanship. A true work of art.',
    price: 199.99,
    originalPrice: 250.00,
    images: [
      '/images/hijab-9-1.jpg',
      '/images/hijab-9-2.jpg',
      '/images/hijab-9-3.jpg',
    ],
    category: 'silk-hijabs',
    colors: ['Gold', 'Silver', 'Bronze', 'Pearl'],
    sizes: ['One Size'],
    inStock: true,
    featured: true,
    tags: ['silk', 'embroidered', 'luxury', 'handcrafted'],
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '10',
    name: 'Everyday Cotton Essential',
    description: 'Essential cotton hijab for everyday wear. Soft, comfortable, and easy to care for. Available in multiple colors.',
    price: 18.99,
    images: [
      '/images/hijab-10-1.jpg',
      '/images/hijab-10-2.jpg',
      '/images/hijab-10-3.jpg',
    ],
    category: 'cotton-hijabs',
    colors: ['Black', 'White', 'Brown', 'Gray', 'Blue'],
    sizes: ['One Size'],
    inStock: true,
    featured: false,
    tags: ['cotton', 'essential', 'everyday', 'affordable'],
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
  },
];
